In [1]:
# imports

import pandas as pd

#Gaussian naive bayes
from sklearn.naive_bayes import GaussianNB

#80%- training and 20% - testing

from sklearn.model_selection import train_test_split

# model accuracy for categories finding: use accuracy score

from sklearn.metrics  import accuracy_score

# to convert output labels into numbers(0 or 1)-label encoder
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("/content/diabetes_prediction_dataset.csv")
df

       gender   age  hypertension  ...  HbA1c_level blood_glucose_level  diabetes
0      Female  80.0             0  ...          6.6                 140         0
1      Female  54.0             0  ...          6.6                  80         0
2        Male  28.0             0  ...          5.7                 158         0
3      Female  36.0             0  ...          5.0                 155         0
4        Male  76.0             1  ...          4.8                 155         0
...       ...   ...           ...  ...          ...                 ...       ...
99995  Female  80.0             0  ...          6.2                  90         0
99996  Female   2.0             0  ...          6.5                 100         0
99997    Male  66.0             0  ...          5.7                 155         0
99998  Female  24.0             0  ...          4.0                 100         0
99999  Female  57.0             0  ...          6.6                  90         0

[100000 rows x 9 columns]

In [3]:
df.head()

   gender   age  hypertension  ...  HbA1c_level blood_glucose_level  diabetes
0  Female  80.0             0  ...          6.6                 140         0
1  Female  54.0             0  ...          6.6                  80         0
2    Male  28.0             0  ...          5.7                 158         0
3  Female  36.0             0  ...          5.0                 155         0
4    Male  76.0             1  ...          4.8                 155         0

[5 rows x 9 columns]

In [4]:
df.tail()

       gender   age  hypertension  ...  HbA1c_level blood_glucose_level  diabetes
99995  Female  80.0             0  ...          6.2                  90         0
99996  Female   2.0             0  ...          6.5                 100         0
99997    Male  66.0             0  ...          5.7                 155         0
99998  Female  24.0             0  ...          4.0                 100         0
99999  Female  57.0             0  ...          6.6                  90         0

[5 rows x 9 columns]

In [5]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [10]:
# input and output

#input(x)

x=df.select_dtypes(include=['int64','float64']).drop(columns=['diabetes'])

#output(y)
y=df['diabetes']

# df.columns

In [11]:
model=GaussianNB()

# to assign output labels such as 0 for no diabetes and 1 for diabetes
le=LabelEncoder()

y_val=le.fit_transform(y)

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y_val)
# now splitting x,y_val - input and output data for testing and trianing

# model training
model.fit(x_train,y_train)

GaussianNB()

In [14]:
# testing
y_pred=model.predict(x_test)
# y_pred

In [16]:
# accuracy score --> it compare actual and predicted values

acc=accuracy_score(y_test,y_pred)

print("Accuracy score: ",acc)

#accuracy:0.9 -> excellent model

Accuracy score:  0.90188

In [19]:
# user prediction inputs
# input features(x): 'age', 'hypertension', 'heart_disease','bmi',
# 'HbA1c_level', 'blood_glucose_level

age=int(input("Enter age: "))
hypertension=int(input("Enter hypertension: "))
heart_disease=int(input("Enter heart disease: "))
bmi=float(input("Enter bmi: "))
HB=float(input("Enter HbA1c_level: "))
blood_glucose=int(input("Enter blood glucose level: "))


user=pd.DataFrame({'age':[age],'hypertension':[hypertension],
                   'heart_disease':[heart_disease],'bmi':[bmi],
                   'HbA1c_level':[HB],
                   'blood_glucose_level':[blood_glucose]})
# user
# predict output
prediction=model.predict(user)

if prediction[0]==1:
  print("You have Diabetes")
else:
  print("You have no diabetes")


# output(y): 'diabetes' --> model predict
# df.columns

Enter age: 25
Enter hypertension: 1
Enter heart disease: 1
Enter bmi: 30.45
Enter HbA1c_level: 6.4
Enter blood glucose level: 120
You have Diabetes