In [3]:
import pandas as pd
# multinomial naive bayes import
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("/content/StudentsPerformance (1).csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [8]:
df["average score"] = (
    df["math score"] +
    df["reading score"] +
    df["writing score"]
) / 3

df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667
1,female,group C,some college,standard,completed,69,90,88,82.333333
2,female,group B,master's degree,standard,none,90,95,93,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,76.333333
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000
998,female,group D,some college,standard,completed,68,78,77,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,83.000000

In [9]:
df["result"] = df["average score"].apply(
    lambda x: 1 if x >= 50 else 0
)

df[["average score", "result"]].head()

   average score  result
0      72.666667       1
1      82.333333       1
2      92.666667       1
3      49.333333       0
4      76.333333       1

In [10]:
# input and output

x = (
    df["gender"] + " " +
    df["race/ethnicity"] + " " +
    df["parental level of education"] + " " +
    df["lunch"] + " " +
    df["test preparation course"]
)

y = df["result"]

In [11]:
vector = CountVectorizer()

x_val = vector.fit_transform(x)

In [12]:
model = MultinomialNB()

In [13]:
model.fit(x_val, y)

MultinomialNB()

In [14]:
print("Model trained successfully")

Model trained successfully

In [ ]:
while True:

    gender = input("Enter gender: ")
    race = input("Enter race/ethnicity: ")
    education = input("Enter parental education: ")
    lunch = input("Enter lunch type: ")
    preparation = input("Enter test preparation course: ")

    student_data = (
        gender + " " +
        race + " " +
        education + " " +
        lunch + " " +
        preparation
    )

    test_student = vector.transform([student_data])

    prediction = model.predict(test_student)

    print("Predicted Result:", prediction[0])

    if prediction[0] == 1:
        print("Student is PASS")
    else:
        print("Student is FAIL")

Enter gender: female
Enter race/ethnicity: group B
Enter parental education:  bachelor's degree
Enter lunch type: standard
Enter test preparation course: completed
Predicted Result: 1
Student is PASS
Enter gender:  male
Enter race/ethnicity: group e
Enter parental education: 12th fail
Enter lunch type: poor
Enter test preparation course: not completed
Predicted Result: 1
Student is PASS
Enter gender: unknown

In [ ]:
import matplotlib.pyplot as plt

subjects = ["Math", "Reading", "Writing"]

average_scores = [
    df["math score"].mean(),
    df["reading score"].mean(),
    df["writing score"].mean()
]

plt.bar(subjects, average_scores)

plt.xlabel("Subjects")
plt.ylabel("Average Score")
plt.title("Student Performance - Average Score by Subject")

plt.show()

In [ ]:
df["average score"] = (
    df["math score"] +
    df["reading score"] +
    df["writing score"]
) / 3

In [ ]:
df["result"] = df["average score"].apply(
    lambda x: "Pass" if x >= 50 else "Fail"
)

In [ ]:
result_count = df["result"].value_counts()

plt.bar(result_count.index, result_count.values)

plt.xlabel("Result")
plt.ylabel("Number of Students")
plt.title("Student Performance - Pass vs Fail")

plt.show()